### ISSUE TITLE
Image built in QEMU hangs on boot (in QEMU)

### ISSUE THREAD

**Issue by JedMeister** [debian-pi/raspbian-ua-netinst#149]
The netinst image that I built (following the help I got in #34) now boots fine, installs everything and finishes cleany.

Then I restart it (with a modified qemu commandline - pretty much the same as I have successfully used on a full raspbian image) and all looks fine during boot, but boot hangs right near the end (I compared it with full raspbian image) just after starting SSH. 

Here is the QEMU commndline I am using:

```
qemu-system-arm -kernel kernel-qemu -cpu arm1176 -m 256 -M versatilepb -no-reboot -append "root=/dev/sda2 rw vga=normal console=ttyAMA0" -hda raspbian-ua-netinst-v1.0.5.img -nographic -redir tcp:5022::22
```

I can SSH in remotely and everything seems fine, but the actual console remains stuck just before it should be offering for me to log in... 

I have done a bit of googling and it seems likely that an init script is hanging. Any ideas of a likely candidate or how I might be able to track down what is happening? Any other debugging hints...?

Note: I haven't done anything else within the new image e.g. as suggested [here](https://github.com/debian-pi/raspbian-ua-netinst#first-boot)

**Comment by 573** [comment]
Hi folks,
I know this thread is long closed, but I am stuck at similar issues today so please allow me one follow-up question.
I am trying to run the netinstaller image according to the preparation of the qemufied raspian image mentioned in the last line of @JedMeister's comment here https://github.com/debian-pi/raspbian-ua-netinst/issues/34#issuecomment-60175822 which is: after all the preparational steps found elsewhere running the first of the two qemu calls namely that with the  `-initrd "installer-qemu.cpio"` parameter to first and foremost run the installer itself I end up with a black qemu window and when using ssh to log into the installation process also an empty console.
Is that the same qemu call you (@JedMeister) were talking about earlier, only asking because the commands you seem to be referring looked slightly different and before I try your findings wanted to make sure they apply in my case.
Cheers up to your good work!

**Comment by JedMeister** [comment]
@573 TBH I don't really recall much in the way of details of my earlier endeavours. Although IIRC following the post you link to, that part all went well. 

It wasn't until I booted the installed system (again in QEMU) that I ran across this issue. 

The commands I used are probably different to most you would come across because I was working on a (remote) headless server via SSH. So I was SSHing into the server, running the QEMU commands, then SSHing into the QEMU server... If you don't need that then you can possibly get away with a less convoluted QEMU command. 

The other thing is that with Jessie things may have changed... I assume that you have compiled your own kernel (for usage in QEMU) and tested with a known good Raspbian OS first?

**Comment by 573** [comment]
@JedMeister thanks for the fast reaction. No I downloaded a kernel for that purpose and will have to look into that kernel-building stuff later I guess.

My overall plan is to use the minimal raspbian as a base for a nginx-served owncloud instance rather than a potentially bloated other image.

So now I want to test the netinstaller (the one with the cpio-packed initrd which turns your raspi into one running a raspbian with minimal packages based on which you can install needed packages AFAIK) without writing it to my sdcard in the first place, hence I need to install this minimal raspbian with the former ones help to the qemu image in place of the sdcard first. BTW I'm fine with sshing requirement. I only needed overall feedback from the installer itself because I have no imagination when the installation was finished successful or not or if it was even started or qemu hangs somewhere etc. I admit I'm a complete newbie on this.

One thing coming to mind looking at your qemu command is I'd rather not forgotten the nographics parameter. I will post you a message on this when I find time in the afternoon to test it.

**Comment by JedMeister** [comment]
If you haven't already, I suggest that you get a vanilla Raspbian img working in your QEMU environment first. Then at least you have a known good base setup. Otherwise I don't really recall but would be glad to hear how things go.

**Comment by 573** [comment]
Based on your findings I repeated the steps for the installer emulation (`installer-qemu.cpio`) with success! I'm happy to proceed with the customisation of the qemu-installed image now.

What I found was that I had to use a kernel for [wheezy](https://github.com/dhruvvyas90/qemu-rpi-kernel/raw/master/kernel-qemu-3.10.25-wheezy) for the emulation rather than the one for [jessie](https://github.com/dhruvvyas90/qemu-rpi-kernel/raw/master/kernel-qemu-4.1.13-jessie) than the installer continued to boot. I would be interested in seeing the reason in the failed case though.

For everything else I used exactly the commands you gave elsewhere ([#34](https://github.com/debian-pi/raspbian-ua-netinst/issues/34#issuecomment-60175822)) with the current raspbian-ua-netinst version accordingly:

    apt-get update && apt-get install xz-utils kpartx
    
    wget https://github.com/debian-pi/raspbian-ua-netinst/releases/download/v1.0.8.1/raspbian-ua-netinst-v1.0.8.1.img.xz
    xzcat raspbian-ua-netinst-v1.0.8.1.img.xz > raspbian-ua-netinst-v1.0.8.1.img
    
    curl http://pastebin.com/raw/sqtQ19Ci | tr -d '\r' > raspbian-ua-netinst-qemu-prep.sh
    ./raspbian-ua-netinst-qemu-prep.sh raspbian-ua-netinst-v1.0.8.1.img

    wget https://github.com/dhruvvyas90/qemu-rpi-kernel/raw/master/kernel-qemu-3.10.25-wheezy
    
    qemu-system-arm -kernel kernel-qemu-3.10.25-wheezy -initrd installer-qemu.cpio -cpu arm1176 -m 256 -M versatilepb -no-reboot -append "root=/dev/sda1 rw vga=normal console=ttyAMA0 console=ttyS0" -hda raspbian-ua-netinst-v1.0.8.1.img -nographic

**Comment by JedMeister** [comment]
Where were you getting your kernels from? You mentioned that you didn't compile your own.

IIRC the QEMU emulation isn't actually an RPi; it's just something vaguely similar. So imagine you'd want to compile a kernel specifically for it. Having said that perhaps thee is something with the Jessie kernel that is an issue for QEMU (or the emulated system)?

**Comment by 573** [comment]
@JedMeister, the kernels are from [qemu-rpi-kernel](https://github.com/dhruvvyas90/qemu-rpi-kernel) here on github. I have added a wget call to download the wheezy kernel to the transcript [above](https://github.com/debian-pi/raspbian-ua-netinst/issues/149#issuecomment-207517520). For the Jessie kernel from the [same repository](https://github.com/dhruvvyas90/qemu-rpi-kernel/raw/master/kernel-qemu-4.1.13-jessie) I can only say qemu didn't progress further than showing a blank window, but I don't know if that is an issue?

At last I compiled the [two edits needed](https://github.com/debian-pi/raspbian-ua-netinst/issues/149#issuecomment-60363628) to the installed generated one image over there at http://pastebin.com/raw/TjNh6K8D by shamelessly stealing from the [work](https://github.com/debian-pi/raspbian-ua-netinst/issues/34#issuecomment-58807067) @dhanar10 did, so you may automate the process if you'd like.

**Comment by 573** [comment]
For booting the installed image then I though use the jessie kernel, so:

    wget https://github.com/dhruvvyas90/qemu-rpi-kernel/raw/master/kernel-qemu-4.1.13-jessie
    qemu-system-arm -kernel kernel-qemu-4.1.13-jessie -cpu arm1176 -m 256 -M versatilepb -no-reboot -append "root=/dev/sda2 rw vga=normal console=ttyAMA0" -hda raspbian-ua-netinst-v1.0.8.1.img -nographic -redir tcp:5022::22

> Welcome to emergency mode! After logging in, type "journalctl -xb" to view
system logs, "systemctl reboot" to reboot, "systemctl default" to try again
to boot into default mode.
Give root password for maintenance
(or type Control-D to continue): 
root@pi:~# uname -a
Linux pi 4.1.13+ #2 Sun Jan 31 11:02:27 IST 2016 armv6l GNU/Linux

Will have to investigate this emergency mode thingy.

**Comment by 573** [comment]
Also after manually editing the `/etc/fstab` and `/etc/modules` entries in the booted up installed image as suggested by @dhanar10 [here](https://github.com/debian-pi/raspbian-ua-netinst/issues/149#issuecomment-60329200) at the first paragraph the emergency mode remains. Somehow I thought these edits were what http://pastebin.com/raw/sqtQ19Ci is about. Maybe I should re-run this part about generating the raspi-installer for qemu.

**Comment by 573** [comment]
Repeated the installer modification that is what I got:

> $ sudo ./raspbian-ua-netinst-qemu-prep.sh raspbian-ua-netinst-v1.0.8.1.img
Image resized.
./raspbian-ua-netinst-qemu-prep.sh: line 39: ../disk-image/boot/installer.cpio: No such file or directory
sed: can't read etc/init.d/rcS: No such file or directory
sed: can't read etc/init.d/rcS: No such file or directory
sed: can't read etc/init.d/rcS: No such file or directory
sed: can't read etc/init.d/rcS: No such file or directory
.
1 block

**Comment by 573** [comment]
The reason for the latest issues posted being that I used the same image file for installing raspbian as coming with the installer latter which apparently has no sda2 partition. I'll inform you about my ongoings.

**Comment by diederikdehaas** [comment]
> I guess installer.cpio is gzipped now, so an edit to the prepare script is needed.

Not only that, but there is a number added to it to indicate for which Pi version it is.
I don't know whether it still works, but this is the relevant part of raspbian-ua-netinst-qemu-prepare which I have now (last edit about 6 months ago):
```sh
mount "/dev/mapper/${LOOP_DEVICE_NAME}p1" "$TEMP_DIR/disk-image/boot"
 
(cd "$TEMP_DIR/disk-image/boot" && gunzip installer-rpi1.cpio.gz)
(cd "$TEMP_DIR/installer" && cpio -iv < ../"disk-image/boot/installer-rpi1.cpio")
(cd "$TEMP_DIR/installer" && sed -i '/^bootdev=/s|/dev/mmcblk0|/dev/sda|' "etc/init.d/rcS")
(cd "$TEMP_DIR/installer" && sed -i '/^bootpartition=/s|/dev/mmcblk0p1|/dev/sda1|' "etc/init.d/rcS")
(cd "$TEMP_DIR/installer" && sed -i '/^rootdev=/s|/dev/mmcblk0|/dev/sda|' "etc/init.d/rcS")
(cd "$TEMP_DIR/installer" && sed -i '/^rootpartition=/s|$|/dev/sda2|' "etc/init.d/rcS")
(cd "$TEMP_DIR/installer" && find . | cpio -H newc -ov > ../"installer-qemu.cpio")
rm -rf "$TEMP_DIR/installer"
```

**Comment by 573** [comment]
Yes @diederikdehaas that's what I did as well. My finding about sda2 above was wrong but it seems as though the kernel thinks on sda2 (the root filesystem) is an ext4 filesystem and can't load a module to handle this thus mounting it readonly, but I still have to look at the logs. Thanks for your finding!

BTW I also commented out, because in the first place I want to boot the installed image on qemu as well, the lines writing the commands to reset the /etc/sda entries back to raspbi device names in postinstall.txt.
