### ISSUE TITLE
Can I specify a proxy?

### ISSUE THREAD

**Issue by GlowTube** [debian-pi/raspbian-ua-netinst#15]
Trying to install jessie via ua-netinst... but I am behind a firewall and must specify an http proxy for external access.  Is there an option in installer-config.txt for this?

At the moment I get

E: Unknown suite jessie

but I suspect this is due to lack of external access, as folks have commented that jessie has been installed successfully via this method before.  Thanks!

**Comment by bennettp123** [comment]
@diederikdehaas Worked fine for me. Thanks for your testing. :)

**Comment by Mausy5043** [comment]
@diederikdehaas I've prepared PR #345 in the hopes of closing this issue.

**Comment by Gurr3** [comment]
My code from installer-config
```
customproxy=proxyuser:proxypass@proxyserver:proxyport/
export http_proxy=http://$customproxy
export ftp_proxy=http://$customproxy
export https_proxy=https://$customproxy
```
which is then echoed into places in post-install
```
echo "http_proxy=http://$customproxy; export http_proxy" >> /rootfs/etc/bash.bashrc
echo "ftp_proxy=http://$customproxy; export ftp_proxy" >> /rootfs/etc/bash.bashrc
echo "https_proxy=https://$customproxy; export https_proxy" >> /rootfs/etc/bash.bashrc

echo "Acquire::http:Proxy \"http://"$customproxy"\";" >> /rootfs/etc/apt/apt.conf.d/50apt-proxy
echo "Acquire::https:Proxy \"https://"$customproxy"\";" >> /rootfs/etc/apt/apt.conf.d/50apt-proxy
echo "Acquire::ftp:Proxy \"http://"$customproxy"\";" >> /rootfs/etc/apt/apt.conf.d/50apt-proxy
```
its also included in rc.local to allow some automatic setup on first boot.

Note that using a password with special characters eg ( or space are required to be url encoded (%28, %20) with this solution

**Comment by Mausy5043** [comment]
:+1: 

Have you tested this? Does the installer run from behind the proxy?
The reason I ask is that you seem to modify the *installed* system. So, I'm wondering how the installer would behave.

**Comment by Gurr3** [comment]
Yes its tested, the installer runs with the changes made in installer-config, eg. `export http_proxy=...`.

The post-install parts is just to carry over into the installed system so it doesn't need to be reconfigured or updated later.

**Comment by Mausy5043** [comment]
:cool: :+1:

**Comment by diederikdehaas** [comment]
Thanks @Gurr3 :+1: Just one question:
> export ftp_proxy=http://$customproxy

Why does the `ftp` proxy start with `http`?

**Comment by Gurr3** [comment]
afaik the protocol specified is what you use to communicate with the proxy, eg. you're not ftp'ing the proxy.
This seems consistent with the [arch wiki scripts](https://wiki.archlinux.org/index.php/Proxy_settings), and looking at them the `https_proxy` should maybe be `http://` as well :confused:

**Comment by diederikdehaas** [comment]
You're right and it makes sense ... in a way. 

OTOH, I still find all the protocol switching odd. Those different protocols were made for a reason.
Also, in the case of https, it also places a lot of trust on the connection to the proxy (if that is over http).
While your browser indicates you're using a secure channel so it's safe to provide your username and password, those will be send in the clear to the proxy. 
Or I have just shown my lack of familiarity with proxies :wink:

**Comment by diederikdehaas** [comment]
@Mausy5043 what's the reason this issue is added to the v1.1.0 milestone?

Milestones indicate that those issues need to be resolved before it gets released ... and I don't consider this item important for it.

**Comment by Mausy5043** [comment]
Based on Gurr3's comments I was under the impression that this could be fixed in v1.1.x. If you think it's more work than I expected feel free to change milestone.

**Comment by goranche** [comment]
setting milestones is not about how much work it's supposed (/expected) to take

**Comment by David-Munnoz** [comment]
Just enabling proxy is not enogh.

The reason is related with time syncronization. It fails in spite of a time server can be declared on installer-config.txt file, but never asked in a proper way.

Most cases, using a proxy server implies the presence of a firewall to isolate traffic and a few additional servers to provide basic network services to the LAN including time sync widely based on ntp protocol. 

At first, rcS script tries obtaining time-sync using ntpdate-debian against default time servers listed on /etc/default/ntpdate file but fails because no one can be reached outside LAN network.

Next, rcS tries using rdate protocol against a list of external timeservers failing for the same reason. It includes $timeserver, but fails again because nobody uses rdate protocol inside a LAN. It was deprecated long time ago due unsecure and unreliable.     

It ends accessing the servers from repository through the proxy, but as announced: "FAILED to set the date, so things are likely to fail now ..." being unable to validate the packages obtained and finaly rcS breaks.

It should be easily solved on further versions adding a few lines at the beginning of time-sync routine, just after date_set=false statement to include the use of ntpdate-debian -b command and the $timeserver in a similar way to the following after some clean style improvements if needed:

	...
	# This will record the time to get to this point
	PRE_NETWORK_DURATION=$(date +%s)

	date_set=false
	# - - -
	 	if [ "$date_set" = "false" ] ; then
	 	# set time with ntpdate & $timeserver
	 	ntpdate-debian -b $timeserver &>/dev/null
	 	    if [ $? -eq 0 ] ; then
	 	        echo -n "Time set using ntp server "$timeserver" to... "
	 	        date
	 	        date_set=true
	 	    else
	 	        echo "Failed to set time, "$timeserver" is unreacheable!"
	 	    fi
	 	fi
	# - - - 
	if [ "$date_set" = "false" ] ; then
	    # set time with ntpdate
	    ntpdate-debian -b &>/dev/null
	    if [ $? -eq 0 ] ; then
	... 

I have already done with flawless results. Sorry, not yet well suited to use the wide github advantages.

And yes, please, use my vote if any value to increase the relevance of support proxified environments when security matters. Also count on with me if can serve to test it as mentioned by @diederikdehaas.

**Comment by David-Munnoz** [comment]
I'm wondering if it should be considered as a new issue because the proposed modification is only related to the coded flow of time synchronization stage in rcS, although required if a specific ntp server need to be declared, ie: behind a firewall as my very own case. Also related at least with issue #6 .

By default the variable $timeserver is loaded with time.nist.gov and code enforces the only use of rdate protocol which should be used as last resource due Raspberry units lack of rtc.

Even ntpdate will be replaced by ntpd in a near future, but at least during the installation process does well and evades the limitations imposed by BusyBox.

This suggested modification is far to be perfect but doesn't interferes with other requirements AFAIK, but solves the problem for those who are constrained behind a firewal because no any administrator will even consider to open port 37.

Please, let me know about your opinions and advices.

**Comment by Mausy5043** [comment]
Current proxy support is not going to change unless someone can provide a working and tested PR.

Closing this issue. If you feel the closure is in error, please feel free to re-open and add new information.
