### ISSUE TITLE
apt-utils

### ISSUE THREAD

**Issue by Mausy5043** [debian-pi/raspbian-ua-netinst#173]
During installing I get:
`debconf: delaying pacakge configuration, since apt-utils is not installed.`

I have this package added to the `packages=` in `installer-config.txt`. So, this got me **wondering**.

 :thought_balloon:  Looking at the names of the packages being unpacked as they scroll by, there seems to be no specific order in which they are installed. I would have expected they would be sorted in order of dependency. But this is not obvious. Is there any way to force a given package to the top of the list? So, it gets installed earlier and perhaps "preventing" messages as the one cited?
Just a thought.

**Comment by JedMeister** [comment]
FWIW debootstrap (and I assume cdebootstrap too) use dpkg to install packages (not apt). It works out the dependencies itself (rather than rely on apt to work them out). It installs the debs with the --force-depends switch which means that they can be installed in any order and so long as all the dependencies are satisfied in the end, then apt won't complain. 

I often use this trick to install a bundle of debs - put them all in a directory and run:
````
dpkg -i --force-depends *.deb
apt-get install -f
````
It's much easier than having to work out what order to install them in...

As for `debconf: delaying pacakge configuration, since apt-utils is not installed.`. My understanding is that the only generally useful script in apt-utils is the `/usr/bin/apt-extracttemplates` which supports interactive configuration *during* install. As we want cdebootstrap to run non-interactively (and just use defaults) there is no value in having apt-utils installed at this stage. Personally I don't have it installed in any of my servers and (other than the warning) everything is fine. It just means that you do the configuration later in the install process...

**Comment by diederikdehaas** [comment]
Thank you for that explanation :+1: 

One possible use case in which `apt-utils`/`debconf` could be useful in the installer, is to use debconf to (pre-)configure packages (and use `--front-end=non-interactive`).
But my attempts in using that were not very successful :wink:

**Comment by JedMeister** [comment]
You can non-interactively configure packages after the fact using dpkg-reconfigure. E.g (using Drupal6 package as an example):
````
debconf-set-selections << EOF
drupal6 drupal6/dbconfig-reinstall boolean true
EOF
DEBIAN_FRONTEND=noninteractive dpkg-reconfigure drupal6
````

**Comment by diederikdehaas** [comment]
Cheers :+1:

**Comment by Mausy5043** [comment]
Thanks @JedMeister for the explanation. I'm now wondering whatever convinced me to install `apt-utils` in the first place :smile: . Can't seem to find at what point or why I started installing that package. So, I'll try to remove that from the list and see what breaks. Obviously, if it has depends it will get installed anyway.
