### ISSUE TITLE
Emailing the log file

### ISSUE THREAD

**Issue by aristosv** [debian-pi/raspbian-ua-netinst#338]
I have set everything up in post-install.txt to be able to sent email, and I have this command in there also.
```
echo -n "Sending Logfile..."
  /rootfs/usr/bin/mail -s "$HOSTNAME Setup Completed" my@email.net < /rootfs/var/log/raspbian-ua-netinst.log
echo "OK"
```

But in the logfile I get this
```
Sending Logfile.../etc/init.d/rcS: /bootfs/post-install.txt: line 78: can't open /rootfs/var/log/raspbian-ua-netinst.log: no such file
OK
```

Is the log file written somewhere else, and copied to /var/log after the installation finishes?

**Comment by Mausy5043** [comment]
yep
https://github.com/debian-pi/raspbian-ua-netinst/blob/master/scripts/etc/init.d/rcS#L3  says:
```
LOGFILE=/tmp/raspbian-ua-netinst.log
```
And then at the end:
https://github.com/debian-pi/raspbian-ua-netinst/blob/master/scripts/etc/init.d/rcS#L690-L691

```
# copy logfile to standard log directory
cp $LOGFILE /rootfs/var/log/raspbian-ua-netinst.log
```

**Comment by aristosv** [comment]
I tried this
```
/rootfs/usr/bin/mail -s "$HOSTNAME Setup Logfile" my@email.net < /rootfs/tmp/raspbian-ua-netinst.log
```
But I got a message saying 
```
can't open /rootfs/tmp/raspbian-ua-netinst.log: no such file
```

I can't use /rootfs/var/log/raspbian-ua-netinst.log because the "send email" command runs before the copying of the log file in /rootfs/var/log

**Comment by diederikdehaas** [comment]
> can't open /rootfs/tmp/raspbian-ua-netinst.log: no such file

That's because it is `/tmp/raspbian-ua-netinst.log`.

@Mausy5043 was kind enough to point the solution out for you ( :+1: ), but IMO you could've easily found it yourself. The whole installation process is coded in https://github.com/debian-pi/raspbian-ua-netinst/blob/master/scripts/etc/init.d/rcS. If there are parts of the installation script that you don't understand, I'm happy to explain it to you and/or improve the documentation, but I do expect you to put a bit more effort into it yourself then you've shown here.

**Comment by aristosv** [comment]
Ok. Thanks.
