### ISSUE TITLE
Additional drivers support (was: USB ethernet dongle support)

### ISSUE THREAD

**Issue by shezzski** [debian-pi/raspbian-ua-netinst#52]
I have a PI with a unusable Ethernet port and are forced to use a USB Ethernet adapter, which is an ASIX AX88178, which works fine normally in Raspbian.  Unfortunately the device does not work with this installer and is unable to obtain an IP via DHCP.  The PI seems to recognise the device in dmesg.  Is it possible to get this to work?

**Comment by diederikdehaas** [comment]
I'm 'merging' issue #319 with this one as it's essentially the same thing.

Thus it's probably a good idea to also include drivers from the 'staging' section, like rtl8188eu, of the kernel source.

**Comment by Mausy5043** [comment]
Is that solving #44?

**Comment by diederikdehaas** [comment]
No, it will only expand the drivers available for the installer kernel a bit, but there's more to it. 

The main problem is that (wireless) drivers are tightly coupled with the kernel version. Since we control the kernel version used during installation, that's not really an issue and including staging drivers should be relatively straightforward. 

But the issue which still needs a proper solution is having wireless drivers for the installed system. For drivers which are part of the kernel source/tree it's still not a problem since they're updated for every release. This means that even if the kernel on the installed system is say 4.3 it should still have working drivers. 

But drivers which are not part of the kernel source, which unfortunately are a lot, that becomes an issue. If the kernel version of the installer and the installed system are the same, we could go for a shortcut and just copy those drivers from the installer to the installed system.
But things will fail when the kernel versions are different between installer and installed system.
What you then actually need are the kernel sources and compile the relevant drivers (or all) on the spot, preferably with [DKMS](http://linux.dell.com/dkms/).

**Comment by Mausy5043** [comment]
Please note that PR #394 (on the v1.1.x branch) now allows users to inject their "own" drivers/modules into the installed system.

**Comment by Mausy5043** [comment]
Please note that PR #397 provides WiFi support to the installer. Would love to hear from @shezzski if this helps.

**Comment by Mausy5043** [comment]
Closing issue, because no response in 4 months. If you feel this problem is not resolved please feel free to re-open and add a comment providing additional information.
